language: go
sudo: required
dist: trusty
go:
  - 1.6
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: "d6K8RO+xSvFGv0mNCl/T9aL4lB9jwTFNV9Vf1S9kNOnxuiumY9VEgQpl6nbLbLSB0KrttDBarHRylP1vR3NIwL5oVuc0bZ+SuRqprLCeXPvJc/FxyaFB9KWiq8WXDtb4q2sH9pTRcfzfmc1bq96AS3xBHEOrvydqgzB+1o7Deoy0idkfuYDVLSedJr1RSxjzr0MY2aktyqHOLu0v+5+hJcZE1zSdrooSWRgB63EniorEKkcUUsmFhyoU3N3bLltzI7dl0gwY295Oi8VqQjtCmb/+d+f7orksKtZsRQhrTnjM6MLgsRDNKc+PnamLcKzRKi5w7OIGvfX0yuOZL/36ISy41MdxT6boILROG7yAWjFhTMYi9ZsA4seuekQETuMOXRqdQta2snfQ+0R9ez4QyJeHsYnP74h5FArylK5VNhjmS2GyTQPoapvrDY2XjqPVTbZGotMxRHMKpEvhZDHsFFNt9aokx23LX+l8JYy/kxLgluGJYOcR2O+lEuiZlHJ2qvWwiNUss0h0vyglXSFfCQuyuk11F8pPL33f7WLqG9hlRh2O82yrjZt7AWGsBSGR4OV2WBAV7Yyx2HNivZLqs5YNrPN3UV23t+FiLiq2X8PRG6tfvpqYbdHUjVtFktDn8lXJTTiltHjBC0Kr9nYYYBV6Gw+oolMmZKWDWGiiVbg="
